export const coffees = [
  {
    id: 1,
    tags: ["tradicional"],
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "tradicional.png",
    price: 9.90,
  },
  {
    id: 2,
    tags: ["tradicional"],
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    img: "americano.png",
    price: 9.90,
  },
  {
    id: 3,
    tags: ["tradicional"],
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    img: "cremoso.png",
    price: 9.90,
  },
  {
    id: 4,
    tags: ["tradicional", "gelado"],
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    img: "gelado.png",
    price: 9.90,
  },
  {
    id: 5,
    tags: ["tradicional", "com leite"],
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    img: "leite.png",
    price: 9.90,
  },
  {
    id: 6,
    tags: ["tradicional", "com leite"],
    name: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    img: "latte.png",
    price: 9.90,
  },
  {
    id: 7,
    tags: ["tradicional", "com leite"],
    name: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    img: "capuccino.png",
    price: 9.90,
  },
  {
    id: 8,
    tags: ["tradicional", "com leite"],
    name: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    img: "macchiato.png",
    price: 9.90,
  },
  {
    id: 9,
    tags: ["tradicional", "com leite"],
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    img: "mocaccino.png",
    price: 9.90,
  },
  {
    id: 10,
    tags: ["especial", "com leite"],
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    img: "chocolate.png",
    price: 9.90,
  },
  {
    id: 11,
    tags: ["especial", "alcoólico", "gelado"],
    name: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    img: "cubano.png",
    price: 9.90,
  },
  {
    id: 12,
    tags: ["especial"],
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    img: "havaiano.png",
    price: 9.90,
  },
  {
    id: 13,
    tags: ["especial"],
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    img: "arabe.png",
    price: 9.90,
  },
  {
    id: 14,
    tags: ["especial", "alcoólico"],
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    img: "irlandes.png",
    price: 9.90,
  },
];